
build:
	docker build -t "sybila/workspace-jupyter-boolean-networks" .

push:
	docker push "sybila/workspace-jupyter-boolean-networks"

run:
	docker run -p 8888:8888 "sybila/workspace-jupyter-boolean-networks"